README.md
These changes were necessary on Ubuntu 14.04
=> Include build tools and dispatch dependencies

Sources/Kitura/Router.swift, Sources/Kitura/RouterElement.swift, Sources/Kitura/RouterRequest.swift, Tests/Kitura/ExternalSubrouter.swift, Tests/Kitura/TestSubrouter.swift, Tests/LinuxMain.swift
See #294 and #333 
I'm doing this as a PR so it can be tested by CI.
TestSubrouter has been added to the test suite.
(Don't need to :P)
=> Implement #294 Subrouters and fixes bug #333

Package.swift, README.md, Sources/Kitura/Router.swift, Sources/Kitura/RouterElement.swift, Sources/Kitura/RouterRequest.swift, Sources/Kitura/RouterResponse.swift, Sources/Kitura/bodyParser/BodyParser.swift, Sources/Kitura/contentType/ContentType.swift, Sources/Kitura/staticFileServer/StaticFileServer.swift, Tests/Kitura/KituraTest.swift, Tests/Kitura/TestContentType.swift, Tests/Kitura/TestCookies.swift, Tests/Kitura/TestErrors.swift, Tests/Kitura/TestMultiplicity.swift, Tests/Kitura/TestResponse.swift, Tests/Kitura/TestSubrouter.swift, Tests/LinuxMain.swift, Tests/net/ClientTests.swift, Tests/net/ParserTests.swift, vagrantfile
Updated version of Kitura that works with 3_24 binaries, works on OSX and Linux.
=> 3 24 migration

Sources/Kitura/bodyParser/BodyParser.swift, Sources/Kitura/staticFileServer/StaticFileServer.swift
Change parse logic In accordance with open close principle 
change valid check from if to guard
in parse function not change code when add other parce function, just append at parserArchiver
If modify or add more parse function, now parse add code like if else, but In accordance OCP not change 
parse code, just implement
print and check data correctly parsed
```swift
import KituraNet
import KituraSys
let router = Router()
router.use(BodyParser())
router.post("/json") {
request, response, next in
response.status(HttpStatusCode.OK).send("Hello, World!")
next()
}
router.post("/text") {
request, response, next in
print("text")
if let body = request.body{
print(body.asText())
response.status(HttpStatusCode.OK).send("Hello, World! \n")
}
next()
}
router.post("/urlencoded") {
request, response, …
```
=> Change parse logic In accordance with open close principle 

Sources/Kitura/RouterElement.swift
Just a pull request for first code change. Removing breaks in switch cases for issue no: #384
=> removed breaks from switch cases for issue no: #384

README.md
change `listen(8090, delegate: router)` to `listen(port: 8090, delegate: router)` in README.md
Swift 3.0 has changed its syntax.
Compile the code in the README.md with the 2016-04-25 snapshot version of Swift.
Swift 3 syntax changed, `listen(8090, delegate: router)` should change to `listen(port: 8090, delegate: router)`
=> Update "Developing Kitura applications" part

README.md
I’ve spent whole night figuring out that the tutorial I followed is out
of date:(
=> Changing to the latest minor version of Kitura in the tutorial.

Sources/Kitura/Error.swift, Sources/Kitura/InternalError.swift, Sources/Kitura/Router.swift, Sources/Kitura/RouterElement.swift, Sources/Kitura/RouterMethod.swift, Sources/Kitura/RouterRequest.swift, Sources/Kitura/RouterResponse.swift, Sources/Kitura/TemplatingError.swift, Sources/Kitura/bodyParser/BodyParser.swift, Sources/Kitura/bodyParser/ParsedBody.swift, Sources/Kitura/contentType/ContentType.swift, Sources/Kitura/staticFileServer/StaticFileServer.swift, Tests/Kitura/TestResponse.swift
Changed enum values to lower camel case. Also streamlined RouterMethod enum with rawValue based initializer.
Fixes #132 
Tests were updated. All now pass
=> camelCase enums based on Swift 3 proposal 36 guidance

Sources/Kitura/RouterRequest.swift, Tests/Kitura/TestResponse.swift
Implemented ```domain``` and ```subdomains``` properties for ```RouterRequest``` class.
IBM-Swift/Kitura#303
Added tests that checks host, domain and subdomains properties
=> Subdomains property for RouterRequest

Package.swift, README.md, Sources/Kitura/RouterRequest.swift, Tests/Kitura/TestContentType.swift, Tests/Kitura/TestCookies.swift, Tests/Kitura/TestErrors.swift, Tests/Kitura/TestMultiplicity.swift, Tests/Kitura/TestResponse.swift, Tests/Kitura/TestRouteRegex.swift, Tests/Kitura/TestSubrouter.swift, vagrantfile
=> 0509 migration

Sources/Kitura/Router.swift, Sources/Kitura/RouterHTTPVerbs.swift, Sources/Kitura/bodyParser/BodyParser.swift, Sources/Kitura/bodyParser/BodyParserProtocol.swift, Sources/Kitura/bodyParser/MultiPartBodyParser.swift, Sources/Kitura/bodyParser/TextBodyParser.swift, Sources/Kitura/bodyParser/URLEncodedBodyParser.swift, Sources/Kitura/staticFileServer/FileServer.swift, Sources/Kitura/staticFileServer/StaticFileServer.swift, Tests/Kitura/TestCookies.swift, Tests/Kitura/TestErrors.swift, Tests/Kitura/TestMultiplicity.swift, Tests/Kitura/TestResponse.swift, Tests/Kitura/TestSubrouter.swift
Removed unused imports from Kitura
Removing unused imports clarifies what the dependencies are to external modules from each class
All tests ran and passed
=> Removed unused imports

README.md
This really trumped me when I was trying to build the example, so I think it'll be useful for everyone else
Issue #555 
)
=> Added the HeliumLogger package description in the Logging step

docker-compose.yml
docker-compose.yml file for issue #564
Makes running Kitura unit tests on Linux as simple as running:
`docker-compose up`
Tested using Docker for Mac 1.12
=> Improve Linux unit testing using Docker

Sources/Kitura/JSONPError.swift, Sources/Kitura/RouterResponse.swift, Tests/Kitura/TestResponse.swift
=> Add JSONP support

Sources/Kitura/RouterResponse.swift
moved onEndInvoked and writtenDataFilter there
=> IBM-Swift/Kitura#505 added Lifecycle struct and a variable

Tests/Kitura/TestResponse.swift
=> Change test to be unambiguous

README.md
=> Fixes #657 so that the instructions are to create an executable 

.travis.yml
To simplify all .travis.yml file to reduce code duplication
We created a script file in the Kitura-Build repo to be called instead of copying the same 4 lines to multiple repo's travis.yml files
Ran the code through Travis CI which builds Kitura on linux and mac
=> Simplifying the travis file

vagrantfile
Updated the toolchain in Vagrant to support 6/20
=> Updated Vagrant to 6/20

.gitmodules, .travis.yml, Makefile, README.md
We are renaming the Kitura-Build repo to Package-Builder.  When all repo's have been
moved over the old Kitura-Build repo will be deleted
Have run the build through travis ci for both link and mac
=> Renamed the Kitura-Build repo to Package-Builder

README.md
=> Updated the helium logger version in README

Sources/Kitura/Kitura.swift, Tests/Kitura/KituraTest.swift
=> Issue 654: Add Kitura.start() and Kitura.stop() and use in KituraTest

.travis.yml
=> Update .travis.yml to support newer Swift snapshots

Tests/KituraTests/TestResponse.swift
Header tests in Kitura worked because of a bug in Kitura-net. That bug was fixed and now they fail.
Fix issue IBM-Swift/Kitura#718
Ran swift test
=> Fix Kitura Header tests

Sources/Kitura/RouterResponse.swift
https://github.com/IBM-Swift/Kitura/issues/372
=> Remove HTTP.statusCodes

Documentation/CodeConventions.md
of raywenderlich.com
removed "No trailing whitespaces at the end of lines" since it is part of the guide now.
=> IBM-Swift/Kitura#254 updated according to swift3 branch

Sources/Kitura/Router.swift, Sources/Kitura/RouterElement.swift, Sources/Kitura/RouterRequest.swift, Tests/KituraTests/TestRouteRegex.swift, Tests/KituraTests/TestSubrouter.swift
Add more unit tests, add logic to correct behavior of `allowPartialMatch`.
#821
More unit tests
=> Fix issue with allowPartialMatch

Documentation/CodeConventions.md
It was added to raywenderlich.com style, swift3 branch.
=> Removed "Newline character at the end of the file" from Code Conventions document

Sources/Kitura/Router.swift, Sources/Kitura/staticFileServer/FileServer.swift, Tests/KituraTests/TestStaticFileServer.swift, Tests/KituraTests/TestStaticFileServer/index with whitespace.html, Tests/KituraTests/TestStaticFileServer/index+@,.html
=> IBM-Swift/Kitura#872 

Sources/Kitura/Kitura.swift, Tests/KituraTests/TestResponse.swift, Tests/KituraTests/TestServer.swift, Tests/LinuxMain.swift
=> Add server tests for Kitura.swift

Sources/Kitura/FileResourceServer.swift, Tests/KituraTests/TestStaticFileServer.swift
- Added test for missing Kitura resource
- Updated FileResourceServer logic to return `.notFound` HTTP status code when file not found
- Fixed typo: "potental"
=> Added test case for uncovered FileResourceServer code, and made minor fixes to FileResourceServer

Sources/Kitura/staticFileServer/ResourcePathHandler.swift, Tests/KituraTests/MiscellaneousTests.swift, Tests/KituraTests/TestContentType.swift, Tests/KituraTests/TestCookies.swift, Tests/KituraTests/TestErrors.swift, Tests/KituraTests/TestRequests.swift, Tests/KituraTests/TestResponse.swift, Tests/KituraTests/TestStaticFileServer.swift, Tests/LinuxMain.swift
Test various parts of Kitura that weren't tested until now
Improve our test coverage and regression tests
Ran Kitura unit tests on Linux and macOS
=> Improve test coverage for Kitura

Sources/Kitura/Router.swift, Tests/KituraTests/TestTemplateEngine.swift
Implementation of https://github.com/IBM-Swift/Kitura/issues/958.
=> Implementation of Issue 958

Tests/KituraTests/KituraTest.swift
=> Initialize Log.logger once across all tests

Tests/KituraTests/TestServer.swift
One of the tests in KituraTests.TestServer was testing the lifecycle callback for server startup failure. The server startup failure was forced by starting the HTTP server and FastCGI server twice. This no longer fails as BlueSocket has added SO_REUSEPORT to the options set when listening on a port. The SO_REUSEPORT option allows multiple processes/threads to listen on the same port.
This PR changes the way the server startup failures are forced by using illegal ports.
Kitura's CI is failing.
Kitura's unit tests were run locally.
=> Change the way server startup failure is forced to use illegal ports.

Sources/Kitura/Kitura.swift, Sources/Kitura/bodyParser/BodyParser.swift, Sources/Kitura/staticFileServer/StaticFileServer.swift
Cleanup some code 
- Used optional chaining instead of if-let optional unwrapping for shorter code.
- Used repeat-while loop to remove code duplication
- Used defer statement to call `next()` in one line instead of making sure to call next on every guard statement
Change is not required. Only for maintainability and readability.
Ran tests locally in macOS 10.12.4, Xcode 8.3.1. No major changes.
=> Cleanup some code

Tests/KituraTests/TestServer.swift, vagrantfile
Standardize by replacing port 8090 with 8080 in Kitura and related repos.
#1069
=> #1069 Replace port 8090 with 8080

Sources/Kitura/Router.swift, Tests/KituraTests/TestTemplateEngine.swift
For issue https://github.com/IBM-Swift/Kitura/issues/1115.
=> added calling setRootPaths on template engines when viewsPath changes

.travis.yml
=> Add Xcode9 and update to 6-29 snapshot on travis #1121

Sources/Kitura/resources/index.html
Change link to TODO sample
#1128 
Link tested to be working in browser
=> Fix broken link to TODO sample

Sources/Kitura/MimeTypeAcceptor.swift
=> Return predictable result for identical parameters for accepts(header:types)

Package@swift-4.0.swift, Sources/Kitura/RouterResponse.swift, Sources/Kitura/bodyParser/JSONBodyParser.swift, Sources/Kitura/bodyParser/ParsedBody.swift, Tests/KituraTests/TestResponse.swift, Tests/KituraTests/TestRouteRegex.swift, Tests/KituraTests/TestRouterHTTPVerbs_generated.swift, Tests/KituraTests/TestStaticFileServer.swift, Tests/KituraTests/TestSubrouter.swift, Tests/KituraTests/TestTemplateEngine.swift
Removes the dependency on SwiftJSON for Swift 4.0 replacing it with Codable.
[#352](https://github.ibm.com/arf/planning-swift-solutions/issues/352)
Unit tests
=> Remove SwiftyJSON Dependency

Sources/Kitura/Kitura.swift
=> Expose allowPortReuse as a configuration option (#1158)

Sources/Kitura/CodableRouter.swift, Tests/KituraTests/TestCodableRouter.swift
Add support for Codable POST requests to respond with an Identifier as well as the created type. The Identifier is then encoded into the Location header.
Currently a server ID for the created object can only be encoded into the object itself. This means that the client either needs to use objects with an Optional for the id or needs to use two different objects.
This allows the ID to be sent back separately using the Location header (which is a standard approach used for REST APIs)
Yes. Tests added and verified to work with KituraKit (pair PR being raised there.
=> feat: allow POST request to return an Id via Location header

Documentation/bluemix-vm/Bluemix.md.backup
Changed 'Bluemix' to 'IBM Cloud'.
=> Rebranding docs

Sources/Kitura/CodableRouter.swift, Sources/Kitura/RouterRequest.swift
Refactor URLEncoded forms to check inside read instead of using new function
=> Url encoded forms

Sources/Kitura/CodableRouter.swift, Tests/KituraTests/TestCodableRouter.swift
Allow Kitura to send any success response for a POST, not just CREATED.
This replaces https://github.com/IBM-Swift/Kitura/pull/1218, and there's some discussion there.
When Kitura receives a POST, its success response is 201 (CREATED). If one explicitly specifies any other success response, such as 200 (OK), it's treated as an error.
Added unit test `testCodablePostSuccessStatuses`. And variations on this logic have been in use at Capital One for months.
=> Allow POST success status codes besides 201 (CREATED)

Sources/Kitura/CodableRouter.swift, Tests/KituraTests/TestCodableRouter.swift
In this PR I am implementing the support for CodableResultClosure with QueryParameters
At the moment the router handler forces the users to use the CodableArrayResultClosure type only. Compilation fails if the application is expecting a Simple Codable type with QueryParameters.
Application needs a Simple JSON object instead of Array of JSON objects.As the current implementation does not allow a SimpleCodable type to be returned , I have implemented the same.
Ran Kitura test-suite with my changes 
- [ x] If applicable, I have added tests to cover my changes.
=> Implementation of CodableResultClosure with QueryParameters

Sources/Kitura/CodableRouter.swift, Sources/Kitura/SwaggerGenerator.swift, Tests/KituraTests/TestSwaggerGeneration.swift
Remove unused parameters from functions and as a consequence, the number of functions has been reduced.
=> Remove unnecessary function parameters

Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift, Sources/Kitura/CodableRouter.swift, Sources/Kitura/SwaggerGenerator.swift
This PR completes the series of changes derived from #1304 (#1316, #1320, #1321).
It does not functionally change any code.
WIP: There are some review comments from the previous PRs that I'd like to address as part of this one.
=> Swagger generation code tidyup

Sources/Kitura/Kitura.swift
Cherry-pick of 0bc9aa0 to `kitura-2.5` branch.
=> Fix: Add locking for Kitura servers (#1377)

Sources/Kitura/contentType/MediaType.swift
Cherry-pick of #1400 to Kitura 2.6.
=> [2.6] fix: Remove hashvalue for swift >= 4.2 (#1400)

Package@swift-4.0.swift, Package@swift-4.1.swift, Package@swift-4.2.swift
This reverts commit e209e0dc07e0c69ba20bc4a25924fe82f9e31e17.
=> Revert "Use KituraNIO 1 on Swift 4 (#1442)"

.travis.yml
=> ci: Update Travis for 2.6 branch, replace dev with 5.0.1

.travis.yml, Sources/Kitura/RouterRequest.swift, Sources/Kitura/RouterResponse.swift, Sources/Kitura/staticFileServer/RangeHeader.swift, Tests/KituraTests/TestCodableRouter.swift, Tests/KituraTests/TestCookies.swift, Tests/KituraTests/TestStaticFileServer.swift
Cherry-pick of #1466 for the Kitura 2.7 release.
=> Cherry-pick of Swift 5.1 support (#1466) for Kitura 2.7

README.md
=> Fix link to https://www.kitura.dev

Package.swift
Ensure KituraContracts depends on the latest community version.
=> Fix incorrect version requirement for KituraContracts

Package.swift, Tests/KituraTests/TestServer.swift
Now use Kitura-NIO rather than Kitura-net.
=> Make Kitura-NIO the default network stack.
