- README.md
I was following the README and it wasn’t clear that I needed to import
the modules into main.swift, this should make it clearer to the next
developer.
> README clarity

- vagrantfile
After the https://github.com/IBM-Swift/Kitura/commit/c30c088d5980d7932fb97c1c57f03506ab926486 commit, which solves [#19 Move from the forked version of libdispatch (maintained by Chris) and use the official one from apple](https://github.com/IBM-Swift/Kitura/issues/19), the vagrant provisioning script stopped working. 
The main reason being that it was still pointing towards the fork of libdispatch, and the modulemap file it was pointing at no longer existing.
I went in and updated the script to work with the new version of it, and I have been able to run the sample app ("You're running Kitura") from just
~~~
> vagrant up
> vagrant ssh
> Kitura/.build/debug/KituraSample
~~~
> Fix vagrant provisioning by running as unprivileged user

- vagrantfile
Made some Ruby code style fixes in vagrant file
Just to conform to the Ruby code style guidelines. Some text-editors with Ruby code style guidelines will not show warnings or errors. 
No tests are required for the Vagrantfile (therefor the functionality has not changed).
> Made some Ruby code style fixes in vagrantfile

- Tests/Kitura/KituraTest.swift
- Tests/Kitura/TestContentType.swift
- Tests/Kitura/TestCookies.swift
- Tests/Kitura/TestErrors.swift
- Tests/Kitura/TestMultiplicity.swift
- Tests/Kitura/TestResponse.swift
- Tests/Kitura/TestSubrouter.swift
Added XCTestExpectation to request handler. Changed how server tests is waiting for requests to finish.
IBM-Swift/Kitura#86
- [] If applicable, I have added tests to cover my changes.
> Added expectations to server request test cases

- Sources/Kitura/RouterResponse.swift
- Tests/Kitura/TestResponse.swift
Added ```link``` method for RouterResponse class.
IBM-Swift/Kitura#311
Added a test in TestResponse.swift file that checks received Link header value for both single and multiple links.
> Link method for RouterResponse

- README.md
The README.md contains instructions on how to clone, build and install libdispatch. That process can actually be simplified slightly by using 'git clone --recursive' rather than clone, submodule init, submodule update.
This simplifies the documentation and install process.
New instructions run and tested locally
- [X ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [X ] If applicable, I have updated the documentation accordingly.
- [NA ] If applicable, I have added tests to cover my changes.
> replace git submodule init/update with clone --recursive

- Sources/Kitura/bodyParser/BodyParser.swift
- Tests/Kitura/TestResponse.swift
Fix for supporting Content-Type with parameters.  Third time's a charm.
Many Internet services will send parameters with Content-Type. For example:
POST /message HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Fixes:
#474
Added unit test testPostRequestUrlEncoded() which tests UrlEncoded POST with and without a Content-Type parameters.
- [ x ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ x ] If applicable, I have added tests to cover my changes.
> Fix for issue #474 + unit test

- Sources/Kitura/RouterResponse.swift
Added as PR so we can discuss. This PR adds an overridable method that will be called when `response.end` is called
This is used for #524. By overriding `onResponseEnd` the middleware can do additional work later in the response lifecycle.
> IBM-Swift/Kitura#524 Added response end hook

- Package.swift
- Sources/Kitura/Kitura.swift
Last piece of the fix for IBM-Swift/Kitura#417. Eliminate the use of dispatch_main
Exploit the new waitOnListeners API in KituraNet.HTTPServer instead of invoking dispatch_main.
**Note:** It is important that this PR not be merged before the PR https://github.com/IBM-Swift/Kitura-net/pull/43 is merged.
On Linux processes running Kitura used to get marked as defunct. This prevented:
1. The use of LLDB to debug
2. Getting core files when Kitura crashed
3. Tools like top didn't report useful information
This was apparently due to the way dispatch_main is implemented on Linux.
This is issue IBM-Swift/Kitura#417
Tested as part of the performance test work, ran Kitura under lldb, and have successfully gotten core files when Kitura processes crash.
> IBM-Swift/Kitura#417 Exploit the new waitOnListeners API in KituraNet.HTTPServer

- README.md
To access the web server it's necessary to forward port 8090 on Docker host to the container.
The Docker description is not complete as the port is not connected to the container. This is rectified by adding a command to forward the port to the Docker container.
It makes it possible for someone to follow the step by step Docker instructions and get the server responding.
The command was tested with Docker.
Tested on macOS version 10.12 beta running Docker version 1.12.0-rc2-beta17
> Forward port on Docker host to the container

- Sources/Kitura/bodyParser/MultiPartBodyParser.swift
- Tests/Kitura/TestResponse.swift
The refactor centers around the addition of an NSData extension function "components". It operates similar to String.components where NSData can be split into an array of NSData elements using a separator. In the case of MultiPart parsing, the separator is the boundary.
String components function:
`func components(separatedBy separator: String) -> [String] { ... }`
New NSData components extension:
`func components(separatedBy separator: NSData) -> [NSData] { ... }`
The new components function may be useful in other parts of Kiitura.
During development of MultiPartBodyParser.swift, there was a goal of an eventual refactor. No functionality was changed.
Tested on Mac and Linux. A new negative test case was added as well.
> MultiPartBodyParser using extension NSData.components

- vagrantfile
Using the vagrantfile to bring up a development image doesn't work - it's looking for the devel branch of Kitura which doesn't exist
Altered the vagrantfile to pull from master instead of devel
Making the install work from vagrant
Installed a system using vagrant up; system came up.
- [N/A ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [N/A ] If applicable, I have updated the documentation accordingly.
- [N/A ] If applicable, I have added tests to cover my changes.
> Change Kitura branch in vagrantfile to master

- Sources/Kitura/Kitura.swift
- Sources/Kitura/Router.swift
- Tests/Kitura/KituraTest.swift
As the title describes, this is a refactoring / renaming of the HTTPServerDelegate class protocol in Kitura-net to simply ServerDelegate. Changes apply to both Kitura and Kitura-net, both on the master branch.
In relation to #565 - adding FastCGI to Kitura.
- Pulled HTTPServerDelegate from the HTTPServer class.
- Placed it in it's own file, ServerDelegate.swift in Kitura-net.
- Replaced all uses of HTTPServerDelegate with ServerDelegate system wide. This affects both the Kitura-Net and Kitura projects.
This class will ultimately be used to provide server protocols other than HTTP and will be used by a forthcoming pull request related to adding a FastCGI server implementation to Kitura. For clarity, this refactor makes it obvious that the ServerDelegate handles more than HTTP and moves it …
> Refactored Kitura-Net HTTPServerDelegate to ServerDelegate

- Sources/Kitura/bodyParser/BodyParser.swift
- Tests/Kitura/TestResponse.swift
return the body is already parsed, e.g. request.body is not nil
added a test case
> IBM-Swift/Kitura#577 in BodyParser check if body is already parsed

- README.md
The instructions for installing libDispatch was good in the sense it was simple for copying and pasting into the Terminal. However, with each toolchain path being different, it might be easier to define the path to the toolchain outside of the configuration command.
Idea comes from lots of experience simplifying the process for myself and others. @chiahuang
> Improved the directions for installing libDispatch

- Tests/Kitura/KituraTest.swift
- Tests/Kitura/PrintLogger.swift
- Tests/Kitura/TestCookies.swift
- Tests/Kitura/TestErrors.swift
- Tests/Kitura/TestMultiplicity.swift
- Tests/Kitura/TestRequests.swift
- Tests/Kitura/TestResponse.swift
- Tests/Kitura/TestSubrouter.swift
In order to fix the failing tests we need some logs.
Added a trivial logger (simpler than HeliumLogger) to the tests. Every test now invokes the doSetUp function to set the logger.
Get a start on fixing or failing builds
> IBM-Swift/Kitura#662 Added a logger to the tests

- Scripts/generate_router_verbs.sh
- Sources/Kitura/RouteRegex.swift
- Sources/Kitura/Router.swift
- Sources/Kitura/RouterElement.swift
- Sources/Kitura/RouterHTTPVerbs_generated.swift
- Tests/Kitura/TestRequests.swift
- Tests/LinuxMain.swift
Fix for url matching problem described in IBM-Swift/Kitura#668. 
This fix adds a ```allowPartialMatch``` parameter for ```Router``` methods that uses middleware as parameter, so it can be passed down to ```RouterElement``` initializer.
Other possible fix is to add query parameters regex expression as attribute to ```RouterElement``` and use it to match set ```queryParameters``` attribute.
Also changed ```LinuxMain.swift``` so it will perform ```TestRequests``` tests on linux.
IBM-Swift/Kitura#668
Added tests (```testCustomMiddlewareURLParameter``` and ```testCustomMiddlewareURLParameterWithQueryParam```) to ```TestRequests``` to check parameters parsing.
> URL matching fix for middleware

- Package.swift
- Sources/Kitura/RouteRegex.swift
- Sources/Kitura/RouterElement.swift
- Sources/Kitura/RouterResponse.swift
Replaced use of KituraSys.StringUtils with equivalent Foundation call.
There is no longer a need for KituraSys.
Ran swift test on both Linux and macOS
> Remove dependency on Kitura-sys

- Sources/Kitura/RouterResponse.swift
Convert Strings to UTF-8 in alternate way that doesn't involve a "temporary" Data strut that is a poor performer on Linux.
Use APIs other than String.data() to convert a String to UTF-8.
Improve performance by removing internal uses of Data.
Kitura Unit tests and TechEmpower performance test.
> Convert from String to UTF-8 without a Data struct

- Sources/Kitura/RouterResponse.swift
`RouterResponse.render()` lacks a `@discardableResult` annotation.
This means that `try response.render("data", context: ["name": "George"])` gives this warning:
`warning: result of call to 'render(_:context:)' is unused`
> IBM-Swift/Kitura#782 Add @discardableResult

- Sources/Kitura/bodyParser/ParsedBody.swift
- Tests/KituraTests/TestResponse.swift
Eliminate the need to use a switch statement to gain access to the information in the ParsedBody enum.
Consumability of Kitura.
Some of Kitura's tests have been modified to use the new APIs.
> Easier access to ParsedBody elements

- Sources/Kitura/RouteRegex.swift
- Sources/Kitura/Router.swift
- Tests/KituraTests/TestRouteRegex.swift
Fix issue with mounting static file server on `/`.
Made changes to regex generation and route path matching. Added more unit tests.
https://github.com/IBM-Swift/Kitura/issues/837
Additional units tests and manually testing.
> IBM-Swift/Kitura#837 Fix issue with mounting on "/"

- Sources/Kitura/bodyParser/MultiPartBodyParser.swift
- Sources/Kitura/bodyParser/Part.swift
- Tests/KituraTests/TestResponse.swift
This modifies `MultiPartBodyParser` so that the `filename` section of `Content-Disposition` is read and stored correctly, if present.
I've duplicated the existing `MultiPartBodyParser` code to parse `name`, and created a new `filename` property in `Part` also based on `name`. I've also modified the multi-part tests to check filename is parsed correctly.
Content-Disposition can optionally include a `filename` field ([more info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)), but this was being ignored by `MultiPartBodyParser`. This change reads and stores `filename` if it's present.
`swift test` passes with no errors. I've modified `testMultipartFormParsing()` to ensure `filename` is being parsed correctly.
> Modified MultiPartBodyParser so that it reads a filename if present

- Sources/Kitura/RouterResponse.swift
The `send(json:)` method of `RouterResponse` attempts to convert a SwiftyJSON object into a `Data` object using `rawData(options:.prettyPrinted)`. This is a throwing method, but in the current code nothing happens if an error is thrown. This patch calls `Log.warning()` to write a message to the logger, if there is one. Given that the user is attempting to send data and it's failing, `warning` seems like an appropriate log level.
I've added one line of code to `send(json:)` that logs the following string at "warning" level: `"Failed to convert JSON for sending: \(error.localizedDescription)"`.
I lost 30 minutes of my evening because send(json:) was silently failing. It may be worth considering whether `send(json:)` should itself be a throwing method, but in the meantime adding a warning …
> Adjusted send(json:) to log a warning if conversion fails.

- Sources/Kitura/RouterRequest.swift
Reduced levels of nesting from 5 to 4 in RouterRequest.queryParameters.
There is currently 1 issue of severity: Error on Codebeat: https://codebeat.co/projects/github-com-ibm-swift-kitura
This change should reduce the problem from an "error" severity to "warning".
All existing tests have passed.
> Reduce conditional nesting in RouterRequest.queryParameters

- Tests/KituraTests/TestTemplateEngine.swift
- Tests/LinuxMain.swift
Created 2 basic tests that exercise the previously untested `render()` and supporting private functions in Router.swift.
No test cases yet for integrating a template engine with Kitura.
Tests created and pass.
> Add test case for template engine functions in Router.swift

- Sources/Kitura/RouterResponse.swift
Kitura provides in RouterResponse life cycle hooks, i.e. places where functions/closures can be invoked during the life cycle of the request. In some cases the closures used to implement these hooks cause object reference loops. This in turn causes memory leaks. 
This PR provides a set of functions to reset the life cycle functions each back to their initial value, a no-op function. This breaks the reference loop and fixes the memory leak.
Fix issue IBM-Swift/Kitura#879
@djones6 Ran memory leak tests and verified the leaks went away.
I also ran the Kitura unit tests on both macOS and Linux.
> Eliminate potential reference loops within RouterResponse lifecycle functions

- Sources/Kitura/Router.swift
Break strong retain cycles in the process() method
Code should be pretty self explanatory.
Graph changes below generated with this fix and https://github.com/IBM-Swift/Kitura-Compression/pull/26 and https://github.com/IBM-Swift/Kitura-Session/pull/29
See leak graph posted in #879 
Test suite still passes.  In running on instruments, I get fewer leaks in "Cycles and Roots".
Before: 
After:
> Break request/response retain cycle. Intended to help #879

- Sources/Kitura/bodyParser/BodyParser.swift
- Sources/Kitura/bodyParser/RawBodyParser.swift
- Tests/KituraTests/TestResponse.swift
`BodyParser` should default a `ParsedBody.raw(Data)` when the `Content-Type` isn't known.
`BodyParser` has a [`parserMap`](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/BodyParser.swift#L31-L34) which designates that text-based `Content-Type`s correspond to a specialized parser (e.g., `application/json` -> `JSONBodyParser`).
If the `Content-Type` was not any of those types, it would fall-through and `nil` out the data from the `RouterRequest` instead of storing the raw data in [`.raw(Data)`](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/ParsedBody.swift#L42) on `ParsedBody`.
I fixed this by following pattern and creating `RawBodyParser` which just slots the data into `.raw(Data)`. `BodyParser` now defaults to passing the …
> Added RawBodyParser for BodyParser default parsing method (#908).

- Sources/Kitura/Router.swift
- Sources/Kitura/RouterElement.swift
- Sources/Kitura/RouterRequest.swift
- Sources/Kitura/staticFileServer/FileServer.swift
- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Deprecate urlComponents because of memory leak and compute it when needed
- Use urlURL instead
Depends on IBM-Swift/Kitura-net#153
See IBM-Swift/Kitura#901
…a memory leak
> Deprecate urlComponents because of memory leak and compute it when needed

- Sources/Kitura/Router.swift
- Sources/Kitura/RouterElement.swift
- Sources/Kitura/RouterRequest.swift
- Sources/Kitura/staticFileServer/FileServer.swift
- Sources/Kitura/staticFileServer/StaticFileServer.swift
Lazily construct the `parsedURL` in `RouterRequest`, to avoid the performance penalty of constructing a `URL` in Kitura-Net until we need it (such as retrieving the full URL of a request, or the query params).
For simple cases such as loading static content, we can skip this cost altogether.
A more comprehensive solution would be to avoid the cost of construction for accessing the query params, however since the long-term solution is to use `URLComponents`, this change is sufficient to solve the regression for the most frequent cases without requiring more changes to the public API.
Part of the solution to #942 (the other part is a change to IBM-Swift/Kitura-net, which makes the construction of the `URL` in `HTTPIncomingMessage` lazy).
I ran the Kitura tests on Linux and they passed.  I …
> Issue 942: Lazy parsedURL for better performance

- Sources/Kitura/contentType/ContentType.swift
Now that we can parse the entire content-type list onLinux, we shouldn't use the dummy list
Eliminate platform specific code where possible
Ran Kitura unit tests on both macOS and Linux.
> Remove dummy content type handling code on Linux

- Sources/Kitura/RouterResponse.swift
Replace String.CompareOptions.regularExpression with a static regex.
This has the same memory leak issue described in #951
See #951
With master branch, memory leak reported by massif for 10,000 calls is **155 MB**
This change drops it down to **96 KB**
> Remove use of String.CompareOptions.regularExpression because of memory leak

- vagrantfile
Use Ubuntu 14.04 as there isn't a Swift 3.0.2 packaged download
for Ubuntu 15.10. Add git to the package install as it isn't part
of the Ubuntu 14.04 base image.
The vagrantfile only installs Swift 3.0 GA, not the latest Swift 3.0.2 build.
https://github.com/IBM-Swift/Kitura/issues/967
I checked that there were no error messages when I created a Ubuntu 14.04 environment using the new vagrantfile (which was tested on macOS).
None of these are required in this instance.
> Update vagrantfile to Swift 3.0.2

- Sources/Kitura/staticFileServer/ResourcePathHandler.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Added a check for the case when the path input is equal to the separator "/".
- Added a unit test to see the getAbsolutePath function would return "/".
#936 
Change includes a unit test to see that when given the input "/", the function returns "/"
> Allow developer to point static file server to system root. (#936)

- Sources/Kitura/Router.swift
- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/TestCookies.swift
- Tests/KituraTests/TestErrors.swift
- Tests/KituraTests/TestMultiplicity.swift
- Tests/KituraTests/TestRequests.swift
- Tests/KituraTests/TestResponse.swift
- Tests/KituraTests/TestRouteRegex.swift
- Tests/KituraTests/TestRouterHTTPVerbs_generated.swift
- Tests/KituraTests/TestServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Tests/KituraTests/TestSubrouter.swift
- Tests/KituraTests/TestTemplateEngine.swift
- Add state guards for RouterResponse end() and send() functions
- Make most unit tests use SSLService as it surfaces socket read, write, close contention problems whereas Socket mostly ignores them
- We still need some fixes in SSLService before we can enable SSL tests. This just requires us to change the default for `sslOption` in KituraTest.performServerTest() from `SSLOption.httpOnly` to `SSLOption.both`
#959
#962
> State guards for RouterResponse end() and send() functions and use SSL tests

- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/MiscellaneousTests.swift
- Tests/KituraTests/TestCookies.swift
- Tests/KituraTests/TestErrors.swift
- Tests/KituraTests/TestMultiplicity.swift
- Tests/KituraTests/TestRequests.swift
- Tests/KituraTests/TestResponse.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Tests/KituraTests/TestSubrouter.swift
There is a lot of forced unwrapping (mostly response related references) in tests which causes a crash when the test fails and the reference is nil. This causes test execution to terminate and subsequent tests to not be run.
We should be able to fix most of the issues by either just removing the forced unwrapping or replacing it with optional chaining, but may require some additional logic in a few cases.
Also, run all tests with SSL as well now that SSLService has added guards against the race conditions that were crashing SSL tests.
#982
#962
#983 
#959
> #982 #962 Avoid forced unwrapping in tests and tests with/without SSL

- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/TestResponse.swift
Kitura Router.handle() calls `response.end()` in case none of the handlers call it, but this is dependent on the route handlers calling next(). Check and ensure RouterResponse end() has been invoked in it's deinitialization so we always end the response when we are done with it.
#1009
> Make sure Response is closed at deinit in case router handlers do not call end() or next()

- Sources/Kitura/RouterRequest.swift
- Sources/Kitura/String+Extensions.swift
- Sources/Kitura/bodyParser/URLEncodedBodyParser.swift
Corrects `URLEncodedBodyParser` dictionary parsing and provides correct representation of query parameter values for `.urlEncoded(...)` body.
Implementing `String` extension `. asUrlEncoded` make a single entry point for `url-encoded` parameters parsing.
I didn't add any new tests. 
Existing test that uses `.queryParameters` and `.urlEncoded(...)` body should cover this changes.
> Unify query string parsing for 'RouterRequest' and 'BodyParser'

- Sources/Kitura/JSONPError.swift
- Sources/Kitura/RouteRegex.swift
- Sources/Kitura/RouterElement.swift
- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/MiscellaneousTests.swift
- Tests/KituraTests/TestErrors.swift
- Tests/KituraTests/TestRequests.swift
- Tests/KituraTests/TestResponse.swift
- Tests/KituraTests/TestRouteRegex.swift
- Tests/KituraTests/TestServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Tests/KituraTests/TestSubrouter.swift
This will let this code compile and run (without warnings) on both swift 3.0.2 and 3.1 (March 15h snapshot).
We can remove this once we start requiring Swift 3.1, but this makes it easier for us to take our time to cut the latest tag once Xcode 8.3 is released.
We can take this or ignore it, but it might make our lives easier.
> Conditional Swift 3.1 support

- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/TestResponse.swift
Large gets and posts on SSL were failing due to various bugs in SSLService and Socket which have now been fixed. These tests add coverage for those issues.
IBM-Swift/BlueSSLService#20
IBM-Swift/BlueSSLService#21
IBM-Swift/BlueSSLService#22
> Test large gets and posts on SSL and non-SSL

- Sources/Kitura/FileResourceServer.swift
- Sources/Kitura/staticFileServer/ResourcePathHandler.swift
Two changes have been made:
1. In the code for the StaticServer middleware add a check for the Kitura repository being under .build/checkouts in addition to possibly being under Packages. These checks are done to find the root of the original repository, when the current directory at execution time is something different.
2. In the code that serves the "landing page", there is code that searches for the resources dircetory which is primarily used when running on Bluemix. In this code a check was added to include looking for the Kitura resources directory under .build/checkouts as well as Packages.
Swift 3.1 by default checks out dependent repositories under ./.build/checkouts. However if one does a `swift package edit .....` on a dependent repository, that repository would be under …
> Add a check for Kitura being under .build/checkouts

- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/TestResponse.swift
For #1057
Set `statusCode` to `OK` if:
1. `invokedSend` is set to `true`, AND
2. `statusCode` is currently `unknown`.
See issue for motivation and context.
Added new test case.
> Set statusCode on invokedSend

- Sources/Kitura/FileResourceServer.swift
Fixes Broken index.html in Bluemix
This change fixes a problem serving the static index.html file in applications running in Bluemix.
With the release of **Swift 3.1**, the `Packages` directory is no longer included, and for backwards compatibility it now checks in both `Packages` and `.build/checkouts` in order to locate the index file.  With the `.build` directory no longer being removed, the file should have been found, but error caused by the missing `Packages` folder terminated the loop before it would check the `.build` directory.  This logic has been reformatted to try to find the file inside the `for` loop.
This changes were tested locally using `swift build` & `swift test`, and in Frankfurt Bluemix.  In order to test that my changes worked in Bluemix, I created a 1.7.3 tag …
> Serve static content

- Sources/Kitura/Kitura.swift
Enables the maximum number of subsequent Keep-Alive requests to be specified when creating an HTTP server.  A value of zero disables Keep-Alive.  A negative value allows unlimited requests, and is the default.
Resolves #1125 
Note that IBM-Swift/Kitura-net#216 is a prerequisite to this one and describes the motivation and context.
See IBM-Swift/Kitura-net#216
> Allow max Keep-Alive requests to be configurable

- Sources/Kitura/bodyParser/JSONBodyParser.swift
- Sources/Kitura/bodyParser/ParsedBody.swift
- Tests/KituraTests/TestResponse.swift
Previously body parser was retaining json objects as .json(Data). This PR changes the case to be .json([String: Any])/
Body parser should hold/make available usable json objects rather than requiring users to convert the data themselves.
unit tests
> Changes Body Parser to hold [String: Any] json obejcts

- Sources/Kitura/Kitura.swift
Exposes the `allowPortReuse` option that was added to Kitura-net in IBM-Swift/Kitura-net#223 to allow Kitura users to opt in to sharing the listener port if this is appropriate for their use case.
A change earlier in the year to BlueSocket meant that Kitura no longer failed to listen on a port that was already in use by another Kitura server, as sockets were initialized with the `SO_REUSEPORT` option.  Prior to this, Kitura would fail to listen on a port that was already in use by another instance.
IBM-Swift/Kitura-net#223 reverts the behaviour for listening ports to disallow sharing by default, and exposes a configuration option on `HTTPServer` and `FastCGIServer` to allow the sharing of the listener port to be enabled again.
This PR adds a new optional parameter `allowPortReuse: Bool` …
> Expose allowPortReuse as a configuration option

- Sources/Kitura/TypeRouter.swift
- Tests/KituraTests/TestBasicTypeRouter.swift
Most basic trimming of internal slashes. Doesn't deal with multiple leading/trailing slashes on path components.
> Add and use simple path join function

- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
This change exposes the document root / base directory used by the StaticFileServer middleware.
The absolute path used for the document root is based on the code in `StaticFileServer.ResourcePathHandler.getAbsolutePath()` and can vary depending on the environment.
In order to work out where the directory is a user would have to reimplement the logic of this non-public code which is inconvenient and brittle to changes in the internals of Kitura.
Instead this PR adds a new property to the StaticFileServer API to provide access to the computed directory.
Tested in an example application and with a simple test case added to `KituraTests/TestStaticFileServer.swift`.
> Expose document root dir used by StaticFileServer

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodableRouter.swift
Changed `contentType == "application/json"` to `contentType.hasPrefix("application/json")`
In Kitura the client requests have a `Content-Type` header, this can have a value like the following: `application/json; charset=utf-8`. The start of the value will always be `application/json` but can have extra information following this. We're currently testing that the value is equal to `application/json` when it'd be more accurate to check whether the start of the value is `application/json`. This can be achieved simply with the `hasPrefix()` call.
This change fixes #1171 
Updated the previous codable routing tests so they now set the content type to `application/json; charset=utf-8` rather than `application/json`. 
This will obviously fail without the change I've submitted but is a more …
> Update isContentTypeJson method

- Tests/KituraTests/TestStaticFileServer.swift
Enable test that was disabled at development time of range requests #1161 
Ensure range requests are always GET
Improve code coverage
Enabling the test :)
> Enable one test for range requests

- Sources/Kitura/String+Extensions.swift
- Tests/KituraTests/TestRequests.swift
Kitura currently does not have array support for query parameters (something that I have always seen in every web framework that I have used in the past).
Developers wanting to map multiple values to a single key as a query parameter in the URL will now be able to do so. This change brings functionality that is commonly found these days in most web frameworks.
A new test function named `testQueryParameters` was added to `TestRequests.swift`. Test cases were executed on macOS and Ubuntu 14.04. Travis CI build is in progress for this PR.
> Added array support to query params.

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodableRouter.swift
I have changed the old array-restricted `get` function to instead allow any `Codable` in the response callback. This means changing the `CodableArrayClosure` for the new `SimpleCodableClosure` which I plan to add to `KituraContracts` in PR https://github.com/IBM-Swift/KituraContracts/pull/4.
This closure type is looser than `CodableArrayClosure`. `CodableArrayClosure` is castable to `SimpleCodableClosure` so the change to the function is not breaking. We no longer need `CodableArrayClosure` but removing it from `KituraContracts` would be a breaking change, so I have left it there for now.
Currently it is not possible to register a Codable `get` handler that doesn't want an id but does respond with a single Codable object (see https://github.com/IBM-Swift/Kitura/issues/1172).
For example, …
> Allow non-array Codables in get without id

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodableRouter.swift
Currently a successfully return from a DELETE action in Codable Routing results in 200 OK. Best practices for REST are that this should return `204 No Content'.
Fixes: https://github.com/IBM-Swift/Kitura/issues/1192
Updated tests to now check for no content rather than OK
> Change codable deletes to return noContent

- Sources/Kitura/staticFileServer/CacheRelatedHeadersSetter.swift
Refix the changes in 2.1.2 as they break on Swift 4.0.0.
`2.1.2` fixes some compile warnings on Linux on Swift 4.0.2/4.0.3 but breaks builds on Swift 4.0.0 (as it takes advantage of a fix in corelibs-foundation that is not present in Swift 4.0.0).
This PR refixes the changes so that the original conditional compile is retained but if further conditional on the Swift version. That is, the old and Linux-specific code path is compiled in on Linux and Swift 4.0.0 but not on macOS (as before) nor on Linux for Swift 4.0.2+.
This change prevents compile errors on Swift 4 in a patch update. Should resolve https://github.com/IBM-Swift/Kitura/issues/1200.
If we want to drop support for Swift 4.0.0 in an upcoming release, we should tag it to reflect the breaking change (at which point we can clean …
> Fix compile error on Swift 4.0.0

- Sources/Kitura/RouterParameterWalker.swift
- Tests/KituraTests/TestRequests.swift
Changing to parameter is removed from list in `RouterParameterWalker.swift` only after all handlers have been dealt with. Previous code was prematurely removing the parameter instead of just reading it, so only the first parameter handler was ever being handled.
Fixes bug in #1209. 
Implemented two new tests as code path wasn't currently being tested. All existing tests still pass.
> Fixing bug for multiple parameter handlers

- Sources/Kitura/CodableRouter.swift
- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/TestResponse.swift
- Tests/KituraTests/TestSubrouter.swift
For issue 574 We are reverting the changes made in #1190 where the send methods were all set to throw. This was a breaking change and so will now be deferred until kitura 3.0.0.
In PR #1190 for the Kitura evolution proposals, we had noticed an inconsistency in error handling. In order to begin bridging this problem, we aligned all the send methods by making them throw and then having to handle them accordingly (mostly in the CodableRouter). As these are breaking changes and we don't want to force our users to migrate to 3.0.0 without any enhanced functionality, we believe this should be deferred until the next major release.
Swift test has been run and all tests passed.
- [x ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x ] If applicable, I have updated the …
> revert recent breaking changes to send

- Package.swift
- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/KituraTestBuilder.swift
- Tests/KituraTests/TestCodableRouter.swift
Add the capability to provide a `Codable` object to `RequestError` that will be encoded and sent by the `Router` as the response body when passed to the completion handler of a codable route.
This PR is one part of a pair, this one is for `Kitura`, the other is for `KituraContracts` (https://github.com/IBM-Swift/KituraContracts/pull/12).
**In the `KituraContracts` PR** we add a new generic constructor to `RequestError` that can specify a "base" request error and a body `Codable`, for example: `RequestError(.unavailable, body: health.status)`.
This will assign the object to a new stored property `body` as a (type-erased) `Codable`. The fact the type is erased allow the `RequestError` struct to remain non-generic (changing it to be generic would be a breaking change to the API).
However, …
> Add RequestError body codable

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodableRouter.swift
Remove code duplication in the CodableRouter and expose CodableHelpers as building blocks for extensions to the CodableRouter.
While working on a prototype codable authentication extension to the router I needed to write variations of the existing route registration functions from CodableRouter. These functions have a lot of code duplication to begin with, and with this new extension each function would need to be duplicated again to add the variations.
This motivated a refactor of these functions so they could be constructed from building block functions. These could then be exposed for use by router extensions.
Automated testing
> Refactor CodableRouter to ease code reuse

- Sources/Kitura/CodableRouter.swift
Mapping the ORM errors to internalServerError to not expose sensitive information about the database
> fix: Map ORM errors to internalServerError

- Sources/Kitura/resources/index.html
Change the reference in the Kitura server landing page (index.html) from Swift-Kuery to Swift-Kuery-ORM.
To promote the newly released Swift-Kuery-ORM github repository ahead of the Swift-Kuery github repo which is currently referenced on the index.html page.
The modified Sources/Kitura/resources/index.html file was placed in the .build/checkouts/Kitura.git-6522211175291160341 directory of a working HelloWorld Kitura application and the changes checked.
> Update index.html to reference Swift-Kuery-ORM

- Sources/Kitura/staticFileServer/StaticFileServer.swift
In this pull request the StaticFileServer and its handle function were changed from being public to being open.
This was done to fix issue #937 and allow you to subclass/override the class.
Kitura tests have been run and all pass.
> fix: make StaticFileServer open class

- Sources/Kitura/Router.swift
Update the `TemplateEngine` docs to provide more information regarding edge cases such as registering multiple different template engines to use the same extension. 
Makes the API docs clearer for users.
> Update Router Templating API docs

- .travis.yml
- Package.swift
Update Kitura's dependencies to minimum levels for Swift 4.1, to ensure a consistent .swift-version across all packages: Kitura-net 2.1, Kitura-TemplateEngine 1.7.4 and KituraContracts 0.0.22.
The minor version constraint is also being removed, as we do not make API breaking changes in a minor release, and retaining it generates unnecessary churn in order to keep dependencies updated.
> Update to Kitura-net 2.1.0 and relax minor constraint

- Sources/Kitura/bodyParser/BodyParser.swift
- Sources/Kitura/bodyParser/ParsedBody.swift
- Tests/KituraTests/TestResponse.swift
Added an as raw helper function to parsed body. 
This means instead of:
if case let .raw(data) = requestBody {}
You can do:
if let data = requestBody.asRaw {}
Which is more readable and now matched the other types (JSON, URLEncoded, text)
Test for bodyparser has been changed to use this helper function and is passing
> Add asRaw to ParsedBody

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodableRouter.swift
This PR applies the logic from #1254 to the TupleArrayOutResultHandler.
#1254 updated the logic for Codable result handlers to check the status class of a `RequestError`.  If it represents a success status, take the successful path but using the specified status code in preference to the default for that method (such as `.created` for POST).
Although that PR was focused on the status code for a POST, it has the nice effect of applying that same logic to all methods, so it is now valid to return a Codable response and any success code in place of a `RequestError`, rather than `nil` as before.  This handler was missed from the original PR as there is no POST method that returns an array of tuples.
A test has been added that explicitly sets the `.ok` status code for a GET on a tuple array.
> Custom success status codes for Tuple return types

- Sources/Kitura/bodyParser/BodyParser.swift
Updated the Jazzy docs for Body parser to say which content type headers match to ParsedBody types.
Have also added a usage example for getting a JSON body
Requested by a user on slack after he was getting nil from the body parser when he wasn't sending a content type header.
Only a docs change so no added tests
> update bodyparser docs example

- Sources/Kitura/RouterRequest.swift
- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/TestResponse.swift
This change adds a `userInfo` property to `RouterResponse`. The associated test checks if one handler can store data in `userInfo` and a subsequent handler can read it.
This supports the use case of building a response in several steps. Handlers/middlewares can store intermediate data in `userInfo` so it can be used by the final handler to build the response.
A test scenario is included.
> Add a userInfo property to RouterResponse

- Package.swift
- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/KituraTestBuilder.swift
- Tests/KituraTests/TestCodableRouter.swift
This reverts #1242.
We've found a problem with the relaxing of output types from `Codable` to `Encodable`, such that they are no longer compatible with the [TypeDecoder](https://github.com/IBM-Swift/TypeDecoder).
We need to revert the relaxing of types so that TypeDecoder can be used with the types used by Codable routes.  Unfortunately, this means #1235 is no longer resolved and should be reopened.  We'll still aim to reintroduce this in the future once a solution can be found.
Note - depends on https://github.com/IBM-Swift/KituraContracts/pull/22
> Revert "Relax Codable Router type requirements"

- .travis.yml
- Sources/Kitura/FileResourceServer.swift
- Sources/Kitura/Router.swift
- Sources/Kitura/staticFileServer/FileServer.swift
- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
Revert changes to serve internal resources using static file server.
Ensure serving path are standardized.
Add further tests to check serving boundaries.
> Issue.843 option2 kitura 2.3

- Sources/Kitura/FileResourceServer.swift
- Sources/Kitura/Router.swift
- Sources/Kitura/staticFileServer/FileServer.swift
- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
Revert changes to serve internal resources using static file server.
Ensure serving path are standardized.
Add further tests to check serving boundaries.
> Serve internal resources using FileResourceServer ensuring path is standardized.

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/KituraTestBuilder.swift
- Tests/KituraTests/TestCodableRouter.swift
This PR reintroduces a change originally developed under #1242 that allows a successful response from a Codable handler with no body (ie. a `nil` return type).
#1254 relaxed the constraints on the return type from a Codable route, to allow response with a custom success code (a `RequestError` representing a status code in the 2xx range) rather than `nil`, which returns a default success status dependent on the method (`.created` for POST, `.OK` for PUT, etc).
As part of #1242 I took this further, and allowed a `nil` body response with either a default (`nil`) or custom (2xx) response code.  In that context it was to allow a POST of a type that could be decoded but not encoded (ie. received, but not sent).  Unfortunately we had to back out #1242, but permitting an empty body as a return …
> Allow Codable success responses with no data

- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodableRouter.swift
This PR enables optional QueryParams structure in `get` and `delete` routes.
When declaring a route with QueryParameters, such as: 
```
router.get("/query") { (query: MyQuery, respondWith: @escaping ([User]?, RequestError?) -> Void) in
```
Currently, we cannot make the query optional, and we would have to declare another route.
This issue resolves this by adding a new closure to the **get** and **delete** accepting an optional QueryParams, so we could write:
```
router.get("/query") { (query: MyQuery?, respondWith: @escaping ([User]?, RequestError?) -> Void) in
```
This route would accept a **get** call on `/query` and `/query?age=5`.
Test have been added.
> feat: Add optional QueryParams in closure for  get and delete

- Sources/Kitura/SwaggerGenerator.swift
Currently, we don't run the TypeDecoder until after the path information has been inserted into the Swagger document.  This means that if the TypeDecoder fails for any reason we can be left with a Swagger document that has references to models that don't exist.
Rework the `registerRoute()` functions so that we attempt the type decodes first, and bail out if they fail. This ensures that we will still generate a valid Swagger document.
> Swagger: improve TypeDecoder failure handling

- Sources/Kitura/SwaggerGenerator.swift
- Tests/KituraTests/Models/Uglifruit.swift
- Tests/KituraTests/TestSwaggerGeneration.swift
Currently, the Swagger generation does not work if a model only contains optional properties.
For example:
```swift
public struct Foo {
public let id: Int?
}
router.post("/", handler: postHandler)
func postHandler(foo: Foo, completion: (Foo?, RequestError?) -> Void ) {
completion(foo, nil)
}
```
This fails because the model serialization code defines `required` as an optional array, and if it's nil the serialization fails.
This PR reworks the code so `required` is non-optional, and uses the empty array if there are no required properties.  Then, check if the array is empty before attempting to serialize it, because serializing an empty `required` array is not valid Swagger.
> Swagger: handle models with only optional properties

- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
Currently, Codable routes which include type-safe middlewares are not included in generated Swagger.
Add the registration of Codable routes which include type-safe middlewares into the Swagger representation.
Note that currently the middlewares themselves are not handled by the Swagger generator, so they will appear in the Swagger as generic routes without any middleware information.  Adding that information will be future work.
> Swagger: register type-safe middleware routes

- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
Add @ escaping to the results closures for TypeSafeMiddleware so users can define escaping closures.
> fix: added escaping to result closure

- Tests/KituraTests/TestRequests.swift
This test fails with IPv6 enabled because `localhost` resolves to `::1` with IPv6. This happens only on Linux, though. We worked around this false failure in `Kitura-NIO` in the wrong way.
> Fix a false failure with IPv6

- Tests/KituraTests/TestResponse.swift
The redirect test in Kitura used to redirect to IBM.com and then search the result for the text IBM. If it found it then it would pass. This caused the tests to fail if IBM.com did not respond. 
This change adds a new route "redirected" and makes the test redirect to this local route instead and check for the correct response.
> Changed redirect test to local redirect

- .swift-test-linux
- .travis.yml
- Sources/Kitura/SSLConfig.swift
- Tests/KituraTests/KituraTest.swift
PR https://github.com/IBM-Swift/Kitura-NIO/pull/58 adds support for PKCS#12 formatted certificates in Kitura-NIO. Hence we can now allow SSL configuration through pfx files on Darwin
> [kitura-nio]Allow pfx files on Darwin

- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
- Sources/Kitura/CodableRouter.swift
- Sources/Kitura/SwaggerGenerator.swift
- Tests/KituraTests/TestSwaggerGeneration.swift
Reworking of the handling of the id parameter, to permit both Int and String types rather than hard-coding `integer`.
This is code from @nhardman in #1304 which I have split into smaller PRs.
This adds new Swagger generation tests for both String and Int type identifiers.
> Improve type handling for id params in generated swagger

- Sources/Kitura/RouterResponse.swift
Currently, RouterResponse.end() always calls addCookies() to add the
Set-Cookie header if required. The code does various pieces of work even
if there are no cookies, such as allocating an array and iterating over
an empty dictionary.
We can avoid all this unnecessary work by checking whether there are any
cookies before calling addCookies().
I've recently been analysing Kitura performance, and the cost of `addCookies()` is significant.
Performance testing Kitura built in debug mode using simple HelloWorld app. Load was driven via wrk with 128 concurrent connections across 4 cores.
Ubuntu 14.04:
```
| Throughput (req/s)      | CPU (%) | Mem (kb)     | Latency (ms)                   | good
Implementation | Average    | Max        | Average | Avg peak RSS | Average  | 99%      | Max      | …
```
> perf: only call addCookies() if there are cookies

- Package.swift
- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
- Sources/Kitura/CodableRouter.swift
- Sources/Kitura/SwaggerGenerator.swift
- Tests/KituraTests/TestSwaggerGeneration.swift
This PR adds support for representing query parameters in generated swagger.
It also changes the definition of the `parameters` for a `SwaggerMethod`  from `SwaggerParameters` to `[SwaggerParameter]?`, which means it can be omitted from the document rather than the generated swagger containing an empty array when no parameters are present.  The existing tests have been modified accordingly.
This is @nhardman's code and is the feature part of PR #1304, from which I have separately extracted and delivered some fixes for identifier types (#1316) and testcase refactoring (#1320).
There are some issues I'm aware of (such as `queryparams` rather than `queryParams`, and a spurious change of `idType` to `idtype`), but this code builds and passes the tests (which include new tests for this …
> Support for query parameters in generated swagger

- Sources/Kitura/SwaggerGenerator.swift
This is generating a lot of noise in CI logs.
> Quieten noisy debug message in Swagger generator

- .travis.yml
- Package.swift
- Tests/KituraTests/TestServer.swift
- build.sh
We recently renamed the erstwhile KituraNIO package to KituraNet. So, we now have a `KituraNet` and a `SwiftNIO-based KituraNet`. This pull request allows Kitura users to switch to using the latter using only an environment variable named `KITURA_NIO`.
The core of the change is only to the Swift package manifest file. In the building phase of the Kitura application, if an environment variable named `KITURA_NIO` is set, the Swift package manager switches to using the NIO-based KituraNet found [here](https://github.com/IBM-Swift/KituraNIO). The other changes in this pull request are in the Tests and mostly around two limitations of the NIO-based port - [a bind issue ](https://github.com/IBM-Swift/KituraNIO/issues/2)and the absence of a FastCGI implementation. 
To enable the use of the …
> Allow users to switch to using the NIO port of KituraNet

- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
- Sources/Kitura/CodableRouter.swift
- Sources/Kitura/SwaggerGenerator.swift
- Tests/KituraTests/Models/Banana.swift
- Tests/KituraTests/Models/FruitColour.swift
- Tests/KituraTests/TestSwaggerGeneration.swift
The swagger document generated by `SwaggerGenerator` does not currently represent array return types (such as those from a GET), although the plumbing is in place for it to do this.
This PR resolves this by adding an `outputIsArray: Bool = false` parameter to `registerGetRoute` and setting this to `true` from each route that has an array-type result handler.
I added tests:
- A test that array return types are declared as `"type": "array"`,
- A test that types that are only used as input types are modelled (covering the fix in #1331),
- A test that nested types (that are referenced by input or output types, but are not top-level types) are modelled.
Also, in the process of adding tests I found some redundant code for starting/stopping an instance of Kitura which is not necessary for …
> Support array response types in generated swagger

- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
- Tests/KituraTests/TestTypeSafeMiddleware.swift
Kitura currently doesn't handle optional QueryParameters correctly when used in conjunction with TypedMiddlewares.
If you define a route that has optional query parameters, eg:
```swift
func getAllHandler(query: ToDoQuery?, completion: @escaping ([ToDo]?, RequestError?) -> Void ) {
ToDo.findAll(matching: query, completion)
}
```
the value of `query` is either an instance of a ToDoQuery struct, or `nil`.
However if you add a type-safe middleware, eg for auth:
```swift
func getAllHandler(auth: MyHTTPAuth, query: ToDoQuery?, completion: @escaping ([ToDo]?, RequestError?) -> Void ) {
ToDo.findAll(matching: query, completion)
}
```
then you actually receive an instance of an Optional ToDoQuery, with all the fields set to nil, eg:
```
Optional(Application.ToDoQuery(name: nil, age: nil))
```
As …
> Handle optional query parameters correctly with typesafe middlewares

- .travis.yml
- Sources/Kitura/DecodingError+Extensions.swift
Switches to the swift-4.2-RELEASE build (on Linux; macOS is already there as Travis has released an xcode10 GM image with the same name - `xcode10` - as the previous betas).
Also resolves a compilation warning since conditional cast of NSError to Error is no longer required on Linux.
> Support Swift 4.2

- Sources/Kitura/Router.swift
- Tests/KituraTests/TestStaticFileServer.swift
This is a redo of #1343 based on feedback in that thread. Whereas the code in that PR implicitly disabled the FileResourceServer for a Router if that Router had any elements/handlers, this PR changes Router to add a new optional `withResourceServer` parameter to its initializer which only starts the FileResourceServer if explicitly set to `true`. 
@djones6 recommended this approach rather than the one I had chosen in the original PR, and I like his idea better than mine too.  As stated there, this may break expected functionality with the Kitura CLI tool.
As with the other PR, existing tests testing the FileResourceServer functionality have been tweaked, and a new test has been added to ensure the functionality is not present by default.
> FileResourceServer must be explicitly enabled when initializing Router

- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer/subfolder/index.html
When StaticFileServer was added as a middleware, and it was added not to the root router but to a sub-router, and it had redirect folders to trailing slash turned on (default setting) then its redirection would be incorrect.
Reproduced Swift 4.0.3 & 4.2; MacOS and Linux
1) Setup a simple Kitura app with a router
2) Add a sample HTML file relative to the project at ./src/users/user_id/settings/index.html
3) Add a StaticFileServer to a sub-router of the main router
router.route("/users/:user_id").get(middleware: StaticFileServer(path: "./src/users/user_id/"))
4) HTTP GET /users/me/settings
Expected to happen... 
- Redirect issued to /users/me/settings/ and then the html file loaded
Actually happened... 
- Redirect issued to /settings/ which does not exist (404)
Extract path of request from …
> [Fix] StaticFileServer request path extraction

- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer/subfolder/index.html
* [Fix] StaticFileServer requestPath redirection bug 
StaticFileServer requestPath now extracted from request.parsedURL rather than request.parsedURLPath as this fixes redirection behaviour to trailing slash paths when the static file server is a middleware for a routed path.
Eg. router.get("/aaa/123", middleware: StaticFileServer(...)) -- GET /aaa/123/bbb would previously redirect to /bbb/ rather than /aaa/123/bbb/ as expected. Similar behaviour was experienced when router.route("/aaa/123").get(middleware: StaticFileServer(...))
* Add tests for static file server on a sub router.
> fix: StaticFileServer request path extraction (#1353)

- Tests/KituraTests/TestCodableRouter.swift
- Tests/KituraTests/TestTypeSafeMiddleware.swift
This PR Removes the mapping from a dictionary to an array when comparing results in tests. This is because the dictionary is unordered which causes the comparison to fail on Swift 5. They have been replaced with arrays of the expected values.
> Remove dictionary mapping in tests

- Sources/Kitura/Kitura.swift
This pull request uses NSLock() to make accessing the static httpServerAndPosts and fastCGIServersAndPorts atomic. 
This makes the creation and deletion of Kitura servers thread safe are requested in issue #1368 
This has been tested by running:
```
KITURA_NIO=1 swift test --sanitize=thread
```
Which used to report 1 warning and now reports none.
> Fix: Add locking for Kitura servers

- .swift-test-parallel
- .travis.yml
- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/TestServer.swift
Provide an option to run Kitura tests in parallel (`swift test --parallel`) supported by the use of ephemeral ports.
Kitura tests that fire up a server have the latter listening at a default port of 8080. This stops us from running the tests in parallel because port collisions happen. If we bind the servers to ephemeral ports, it is possible to run the tests in parallel. This pull requests adds support to optionally use ephemeral ports (through the `USE_EPHEMERAL_PORTS` compiler flag). It also adds some travis CI tests that use ephemeral ports and the run in parallel.
Adds an option to run tests in parallel, showcases the use of ephemeral ports, with both KituraNet and KituraNIO
The following test scenarios have been added to travis.yml
1.  Parallel tests(ephemeral ports) with KituraNet …
> tests: Use ephemeral ports in Kitura tests

- .travis.yml
Ask `Package-Builder` to install libressl when using Kitura-NIO on macOS
`Package-Builder`  has been changed to not install libressl by default. It is installed only when asked for, using the `BREW_INSTALL_PACKAGES` env variable.
See https://github.com/IBM-Swift/Package-Builder/pull/157
> macos: install libressl when building with Kitura-NIO

- Sources/Kitura/RouterResponse.swift
The code in `RouterReponse.send(_ str:)` does an unnecessary allocate and copy of the `String` into an intermediate buffer, before writing to the `BufferList`.  This is suboptimal on all Swift versions but especially Swift 5 where the native string backing is UTF-8, so writing into the `BufferList` can be optimised down to a straight `memcpy()`.
Performance testing of this change for "Hello World":
```
| Throughput (req/s)      | CPU (%) | Mem (kb)     | Latency (ms)                   | good
Implementation | Average    | Max        | Average | Avg peak RSS | Average  | 99%      | Max      | iters
---------------|------------|------------|---------|--------------|----------|----------|----------|-------
base_421 |    65371.8 |    67103.4 |    97.4 |        25718 |      1.9 |      5.6 | …
```
> Avoid copy in RouterResponse.send(str)

- Tests/KituraTests/TestServer.swift
Recently we have seen some CI failures (example [here](https://travis-ci.org/IBM-Swift/Kitura/jobs/486165105)) like this:
```
[VERBOSE] [Kitura.swift:143 start()] Starting a FastCGI Server on port 9000...
/home/travis/build/IBM-Swift/Kitura/Tests/KituraTests/TestServer.swift:116: error: TestServer.testServerStartStop : failed - Error code: -9992(0x-2708), Address already in use
[ERROR] [Kitura.swift:147 start()] Error listening on port 9000: Error code: -9992(0x-2708), Address already in use. Use server.failed(callback:) to handle
```
I suspect this is because the FastCGI testing is not using ephemeral ports so when we do `swift test --parallel` we can get collisions on those tests.
Change the tests so it specifies port `0` and hence uses ephemeral ports.
> Use ephemeral ports for FastCGI testing

- Sources/Kitura/RouterRequest.swift
- Sources/Kitura/bodyParser/MultiPartBodyParser.swift
- Sources/Kitura/contentType/ContentType.swift
- Sources/Kitura/staticFileServer/FileServer.swift
A few places in Kitura we use `str.data(using: .utf8)` to create a `Data`. Currently in Swift 5 this is not optimised and goes via a UTF-16 `NSString`.
Instead, use the `Data` initializer which accepts a `Sequence`. This has a fastpath for UTF-8 already.
> Use UTF8View to create Data

- Sources/Kitura/contentType/MediaType.swift
- Tests/KituraTests/TestMediaType.swift
I've been testing my Kitura server and crashed it with:
```
curl -X "POST" "[ENDPOINT_URL]" \
-H 'Content-Type: ' \
-d $'{}'
```
It fixes server crash
Just send a request with empty Content-Type.
> Fix crash when empty MediaType is passed in request

- Sources/Kitura/SwaggerGenerator.swift
- Tests/KituraTests/TestSwaggerGeneration.swift
This PR improves Kitura's generated OpenAPI document with a more accurate status code for responses based on the method:
- GET, PUT, PATCH and DELETE respond with `200: OK`,
- POST responds with `201: Created`,
- POST and PUT can respond with `415: Unsupported Media Type` or `422: Unprocessable Entity` if the content-type / payload are not acceptable or decodable,
- Routes that consume query params can respond with `400: Bad Request` if the query params cannot be decoded,
- Routes that consume body data (PUT and POST) can respond with `500: Internal Server Error` if BodyParser was erroneously used to consume the body data.
I added default descriptions for each of these response types and associated them with their respective routes,  and removed the (unused) attempt at representing a …
> Document standard Kitura responses in generated swagger

- Sources/Kitura/RouteRegex.swift
- Sources/Kitura/String+Extensions.swift
Replaces the use of `String.components` with `String.split` when processing the query parameters string, and replaces the use of `String.replacingOccurrences` with a new function that uses `String.replaceSubrange` instead.
I did attempt to replace the `removingPercentEncoding()` function with a version using only stdlib functions, however I could not get this to outperform the Foundation implementation consistently on Mac and Linux.  For reference, the implementation I came up with (based on CoreFoundation) was:
https://github.com/IBM-Swift/Kitura/compare/ef0e241de858e96e4165b4d4250b16627288488a...177d74eb010261ee194b40f2b2203d00243f0d88
Avoids bridging to NSString.  (see #1388)
> Avoid NSString functions in query params

- Tests/KituraTests/TestStaticFileServer.swift
Several tests that rely on `StaticFileServer` currently fail when running under Xcode.  Two of these tests contain force-unwraps that cause a crash instead of test failure.
This PR removes the force-unwraps from these tests, so that the test suite can be run to completion.  It does not fix the underlying problem that the path to the resources for the StaticFileServer in the tests is invalid when running under Xcode (see #1427).
Tests should not crash, even if they are failing for some reason.
> tests: Remove force-unwraps

- .travis.yml
As Swift.org builds for Ubuntu 14.04 are still being produced, and extended (paid) support is available past the imminent end-of-life date, I'm restoring one build permutation so that we maintain coverage for the core Kitura dependencies.
Similar coverage will be maintained in Kitura-Sample.
> Maintain CI testing for 14.04

- Package@swift-4.0.swift
- Package@swift-4.1.swift
Currently our `Package@swift-4.2.swift` specifies TypeDecoder 1.3.  This is so that the Swagger generator can take advantage of `ValidSingleCodingValueProvider` if it is used.
For consistency, we should make the same version required when building on Swift 4.0 and 4.1.
> Require TypeDecoder 1.3 on Swift 4.0 and 4.1

- .travis.yml
- Package.swift
- Package@swift-4.0.swift
- Package@swift-4.1.swift
- Package@swift-4.2.swift
- Sources/Kitura/Kitura.swift
- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/KituraTestBuilder.swift
- Tests/KituraTests/TestRequests.swift
- Tests/KituraTests/TestServer.swift
Depends on https://github.com/IBM-Swift/Kitura-NIO/pull/187 / https://github.com/IBM-Swift/Kitura-net/pull/296
Adds the ability to listen on a Unix domain socket, rather than an INET (TCP) port.
Tests added.  Updated KituraTest to run existing tests over Unix domain sockets.
> Support Unix domain sockets

- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/MiscellaneousTests.swift
- Tests/KituraTests/TestBridgingHTTPStatusCode.swift
- Tests/KituraTests/TestBridgingRequestError.swift
- Tests/KituraTests/TestCodableRouter.swift
- Tests/KituraTests/TestContentType.swift
- Tests/KituraTests/TestCookies.swift
- Tests/KituraTests/TestCustomCoders.swift
- Tests/KituraTests/TestDecodingErrorExtension.swift
- Tests/KituraTests/TestErrors.swift
- Tests/KituraTests/TestLinuxSafeguard.swift
- Tests/KituraTests/TestMediaType.swift
- Tests/KituraTests/TestMultiplicity.swift
- Tests/KituraTests/TestRangeHeader.swift
- Tests/KituraTests/TestRangeHeaderDataExtensions.swift
- Tests/KituraTests/TestRequests.swift
- Tests/KituraTests/TestResponse.swift
- Tests/KituraTests/TestRouteRegex.swift
- Tests/KituraTests/TestRouterHTTPVerbs_generated.swift
- Tests/KituraTests/TestServer.swift
- Tests/KituraTests/TestStack.swift
- Tests/KituraTests/TestStaticFileServer.swift
- Tests/KituraTests/TestSubrouter.swift
- Tests/KituraTests/TestSwaggerGeneration.swift
- Tests/KituraTests/TestTemplateEngine.swift
- Tests/KituraTests/TestTypeSafeMiddleware.swift
Many of Kitura's tests are missing from the `allTests` definition in their respective test classes, and so do not get picked up by XCTest on Linux.
There is actually a test designed to catch this: TestLinuxSafeguard is a macOS-only test that verifies that the count of tests returned by `XCTestCase.defaultTestSuite` is equal to the number declared in `allTests` (doesn't check the names of the tests, but good enough).
Unfortunately there are two problems with that test:  it doesn't automatically pick up new test classes - so must itself be updated manually when new sets of tests are added - and it was disabled back when Swift 4 had an issue.
This PR re-enables the safeguard test, guarded to run on Swift 4.1 or higher, and changes the way the test is written to remove a lot of code …
> Enable all tests on Linux

- Tests/KituraTests/TestStaticFileServer.swift
This PR updates the StaticFileServer tests to ensure they pass when run from a Kitura project which is an edited dependency of another project.
The root cause of failure relates to the testcases using relative paths to determine where to serve content from. I have updated the tests to calculate the base serving path based upon the location of the test source.
> Ensure StaticFileServer tests pass when edited dependency

- Package.swift
- Package@swift-4.0.swift
- Package@swift-4.1.swift
- Package@swift-4.2.swift
- Sources/Kitura/Kitura.swift
- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/TestServer.swift
This fixes https://github.com/IBM-Swift/Kitura/issues/1450.
Add address parameter to `Kitura.addHTTPServer()` and `Kitura.addFastCGIServer()` which are passed to Kitura-Net and Kitura-NIO for `Server.listen()`.
Feedback is very welcome, especially if I accidentally missed some of your coding convention. I would pay special attention to the parameter order that I used for the methods.
This is necessary to fix https://github.com/IBM-Swift/Kitura/issues/1450.
Manual testing by myself. I also modified the test harness to use the new code path.
> Add option to only listen on one address

- .travis.yml
- Sources/Kitura/RouterRequest.swift
- Sources/Kitura/RouterResponse.swift
- Sources/Kitura/staticFileServer/RangeHeader.swift
- Tests/KituraTests/TestCodableRouter.swift
- Tests/KituraTests/TestCookies.swift
- Tests/KituraTests/TestStaticFileServer.swift
Resolve compilation errors and warnings relating to changes in the Swift 5.1 release:
- `import FoundationNetworking` on Linux to access `HTTPCookie` and similar types, due to [changes to Foundation structure](https://forums.swift.org/t/foundationnetworking/24769)
- fix compilation warnings relating to `var`s that were never mutated
- Temporarily disables two of the TestCodableRouter tests that have extremely long compile times with Swift 5.1 on Linux (reported under: https://bugs.swift.org/browse/SR-11012)
Depends on https://github.com/IBM-Swift/Package-Builder/pull/169 to deploy workaround for running 5.1 snapshot in Docker on Travis.
> Swift 5.1 support

- Sources/Kitura/resources/index.html
Removes BluePic link (which is no longer being maintained) from the Kitura landing page.
Fixes: #1470
Run landing page within a local app as shown here ->
> Remove BluePic from Kitura landing page

- .travis.yml
Travis recently published an `xcode11` macOS image.  This enables the macOS 5.1 CI testing.
> ci: Enable xcode11 build

- Sources/Kitura/staticFileServer/FileServer.swift
- Sources/Kitura/staticFileServer/StaticFileServer.swift
- Tests/KituraTests/TestStaticFileServer.swift
Add a StaticFileServer option to fallback to the index page
This commit adds a new option to the `StaticFileServer.Options` class to enable
fallback to the index.html. This is intended to be used only by single page
applications. Just before the static file server returns a 404, we check if
this option is configured and serve the default index page if it is. The webapp
takes care of the rendering.
Single page applications use only one index file that is accessible by web
browsers, which is usually the index.html, which also serves as a landing page.
All the other pages are accessible only from the landing page. If the users
bypasses the index page to directly visit an inner page, or if they try to
refresh an inner page, the static file server returns a 404  error. Some SPAs
might wish to …
> Add a StaticFileServer option to fallback to the index page

- Sources/Kitura/SwaggerGenerator.swift
add ios availability in SwaggerGenerator
#available(OSX 10.13, *) -> #available(OSX 10.13, iOS 11.0, *)
I'll try to compile latest version of Kitura for iOS, but it were compilation errors.
https://github.com/IBM-Swift/Kitura/issues/1422
nothing :)
> add ios availability

- .swiftlint.yml
- Sources/Kitura/AdditionalCookieAttribute.swift
- Sources/Kitura/OptionalCookieAttribute.swift
- Sources/Kitura/RouterResponse.swift
- Tests/KituraTests/TestCookies.swift
A convenience API to create and add cookies.
The new public enum `CookieAttribute` is created with cases that represent the attributes of a cookie. The `addCookie` function takes an array of  type `CookieAttribute` and returns either an HTTPCookie object or nil, depending on whether foundation HTTPCookie initializer passes or fails. Each attribute in the array is added into the dictionary `cookieProperties` with appropriate keys. The attributes having nil values are not added. This `cookieProperties` dictionary is then passed to the HTTPCookie initializer. If this initializer returns a new  HTTPcookie object, with the given properties, the HTTPCookie object is added to the `cookies` dictionary which contains set of cookies to return with the response. If the initializer fails then a …
> A convenience API to create and add cookies.

- Sources/Kitura/CodableRouter+TypeSafeMiddleware.swift
- Sources/Kitura/CodableRouter.swift
- Tests/KituraTests/TestCodablePathParams.swift
- Tests/KituraTests/TestCodableRouter.swift
- Tests/KituraTests/TestLinuxSafeguard.swift
- Tests/LinuxMain.swift
https://github.com/IBM-Swift/Kitura/pull/1310 added a warning if a user registers a Codable route that accepts an `Identifier` but does not explicitly declare the trailing `:id` path parameter.
Unfortunately, the implementation there was flawed, and although supplying a trailing path parameter silences the warning, the route had a duplicate `:id` parameter appended, such that:
- `/codable` was registered (with a warning) as `/codable/:id`
- `/codable/:id` was (erroneously) registered as `/codable/:id/:id`
This PR resolves this so that `/codable/:id` is correctly registered.  It also adds tests that were missed from the previous PR, and fixes an existing (misleading) test that asserted that registering an explicit `:id` should fail (the test continued to pass, but only as a side-effect of …
> fix: Correctly register Codable routes with trailing `:id`

- Tests/KituraTests/TestCodableRouter.swift
Removes the workaround (disabling two tests) with Swift 5.1 due to slow compilation (https://bugs.swift.org/browse/SR-11012), which was causing our Travis to time out.  This issue is now resolved in the latest snapshots (tested with 5.1 2019-09-16-a).
Restores test coverage.
> tests: Remove workaround for SR-11012

- Package.swift
- Package@swift-4.0.swift
- Package@swift-4.1.swift
- Package@swift-4.2.swift
- Sources/Kitura/Kitura.swift
- Tests/KituraTests/KituraTest.swift
- Tests/KituraTests/TestCodableRouter.swift
- Tests/KituraTests/TestLinuxSafeguard.swift
- Tests/KituraTests/TestResponse.swift
- Tests/KituraTests/TestServerOptions.swift
- Tests/LinuxMain.swift
This PR allows a `requestSizeLimit` (maximum bytes for the request body) and `connectionLimit` (on total number of concurrent connections) to be configured when registering a server.
Example usage from Kitura is as follows:
```swift
let options = ServerOptions(requestSizeLimit: 100, connectionLimit: 3)
Kitura.addHTTPServer(onPort: port, with: router, options: options)
```
If you do not specify either of the parameters, or do not specify a `ServerOptions` at all, then default values are used.  The defaults are defined as constants `ServerOptions.defaultRequestSizeLimit` and `ServerOptions.defaultConnectionLimit`.
- These have been given conservative defaults of 100mb and 10,000 connections, so as to not break existing deployments.
If a client sends a request that exceeds the limit, then …
> feat: Ability to limit request size and connection count
